// CORE

#pragma once

#include "../nt/ntapi.h"

#define CODE_STATUS CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0001, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CODE_PROCESS_ID CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0002, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CODE_PML4 CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0003, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CODE_MODULE_BASE CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0004, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CODE_SECTION_BASE CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0005, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CODE_READ_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0008, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CODE_WRITE_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0009, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CODE_MOUSE_INIT CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0012, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CODE_MOUSE_EVENT CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0013, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CODE_FRAME_INIT CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0014, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CODE_FRAME_RECT CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0015, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CODE_FRAME_FILL CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0016, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CODE_FRAME_METRICS CTL_CODE(FILE_DEVICE_UNKNOWN, 0xde4d0018, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _INFO_STRUCT
{
	ULONG status;

	char process_name[32];
	ULONG process_id;
	uintptr_t pml4;

	wchar_t module_name[32];
	void* module_base;
	bool is64bit;

	void* address;
	void* buffer;
	size_t size;

	long x;
	long y;
	unsigned short button_flags;

	unsigned char r, g, b;
	int width;
	int height;
	int thickness;
}INFO_STRUCT, * PINFO_STRUCT;